apiVersion: v1
kind: Pod
metadata:
  name: cxi-test
  labels:
    app: test
spec:
  containers:
    - name: cxi-test-container
      image: nicolaka/netshoot
      command:
        - sleep
        - "3600"
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
          beta.hpe.com/cxi: "2" # requesting four NIC
        limits:
          cpu: "100m"
          memory: "128Mi"
          beta.hpe.com/cxi: "2" # requesting four NIC